/* 
File Name   : 05_monthly_department_revenue_report.sql
Created On  : 09-Feb-2026
Database    : Hospital
*/


/*
Problem Statement:

The hospital currently lacks an automated and efficient mechanism to generate monthly revenue
reports by department. As a result, management cannot easily track financial performance,
monitor revenue trends, or make data-driven business decisions.

To address this limitation, this script creates a Stored Procedure that extracts and calculates
monthly revenue generated by each department based on billing and appointment records.

The Stored Procedure enables reusable, consistent, and automated revenue reporting without
requiring manual query execution each time. This improves reporting efficiency, ensures accuracy,
and supports financial analysis and strategic planning.
*/



CREATE PROCEDURE Monthly_Revenue
(
	@input_year INT,
	@input_month VARCHAR(10)
)
AS
BEGIN
	SELECT Department_Name,
		   SUM(Amount) AS Revenue_Generated
	FROM
	(
		SELECT B.Bill_ID, B.Bill_Date,
			   DP.Department_Name, B.Amount, B.Paid
		FROM Bill AS B
		left join
		Appointment AS A
		ON B.Appointment_ID = A.Appointment_ID
		left join
		Doctor AS D
		ON A.Doctor_ID = D.Doctor_ID
		left join
		Department DP
		ON D.Department_ID = DP.Department_ID
		WHERE B.Paid = 1
	) AS T
	WHERE
		DATENAME(MONTH,Bill_Date) = @input_month
		and
		DATENAME(YEAR,Bill_Date) = @input_year
	GROUP BY Department_Name
	ORDER BY Revenue_Generated DESC
END
